# configuration file

# SPDX-License-Identifier: BSD-4-Clause-Clear
# Copyright (c) 2018-2019 Qualcomm Technologies, Inc.
# All rights reserved.
# Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:
#    Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#    All advertising materials mentioning features or use of this software, or any deployment of this software, or documentation accompanying any distribution of this software, must display the trademark/logo as per the details provided here: https://www.qualcomm.com/documents/dirbs-logo-and-brand-guidelines
#    Neither the name of Qualcomm Technologies, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
# SPDX-License-Identifier: ZLIB-ACKNOWLEDGEMENT
# Copyright (c) 2018-2019 Qualcomm Technologies, Inc.
# This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.
# Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
#    The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment is required by displaying the trademark/logo as per the details provided here: https://www.qualcomm.com/documents/dirbs-logo-and-brand-guidelines
#    Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.
#    This notice may not be removed or altered from any source distribution.
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#
# DRS v1.0.0 Global configs
#

# DIRBS Core configurations
dirbs_core:
  base_url: 'DIRBS_CORE_BASE_API'


# DRS global configurations
global:
  # minimum govt identification number length to be used
  gin_length: 8

  # user phone number minimum length
  num_length: 8

  # minimum and maximum global imei lengths
  min_imei_length: 14
  max_imei_length: 16

  importer: 1000000
  exporter: 1000000

  # minimum and maximum global msisdn lengths
  min_msisdn_length: 13
  max_msisdn_length: 15

  # maximum no imei per file in case of Registration/De-registration
  max_imei_per_file: 1000000

  #maximum on imei per device
  max_imei_per_device: 5

  #URLS
  core_api_v1: 'CORE_VERSION_ONE_API'
  core_api_v2: 'CORE_VERSION_TWO_API'


  #Directories
  dereg_sample_file: './deregistration/dereg_sample_file'
  reg_sample_file: './registration/reg_sample_file.tsv'
  upload_directory: 'UPLOAD_DIRECTORY'

  #languages support
  supported_languages:
    - es
    - en
    - id
  default_language: en

# DRS configurations for list generations
# Configurations should be defined when deploying the software.
lists:
  # directory path to generate the list,
  # only absolute paths to the directories are acceptable
  path: ''

  # maximum number of workers used for the list generation
  # typically it should be 2 x num_of_cpus in the system
  max_workers: 10

# Postgresql settings used to build SqlAlchemy connection string and configs
database:
  # Database name (an empty database on the first run)
  database: drs
  # Host the PostgreSQL server runs on
  host: drs_db
  # PostgreSQL port if not running on standard port 5432
  port: 5432
  # Database role/user that DRS will connect to
  user: drs
  # Password used to connect to the database
  password: drs
  # SQLAlchemy connection pool size, the number of connections to keep open inside
  # the connection pool
  # (for more details: https://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine
  pool_size: 100
  # number of seconds to wait before giving up on getting a connection from the pool
  pool_timeout: 20
  # number of seconds for pool to recycle the connections after the given number of seconds has passed
  pool_recycle: 10
  # number of max connections to overflow the pool size
  max_overflow: 275

# Different server configuration to enable based on need
server:
  # To restrict https only, it will tell the client to convert all http requests to https
  # it will help in preventing MITM attacks.
  # value should be either "True" or "False"
  restrict_https: True

# celery configurations
celery:

  RabbitmqUrl: 'pyamqp://'
  RabbitmqBackend: 'amqp://'

  RedisUrl: 'redis://'
  RedisBackend: 'redis://'

  RpcUrl: 'rpc://'
  RpcBackend: 'rpc://'

  CeleryTasks: ['app.api.v1.reports_generator']

conditions:

  - name: 'condition_name'
    reason: 'reason_to_be_non_compliant_w.r.t_condition'

  - name: 'condition_name'
    reason: 'reason_to_be_non_compliant_w.r.t_condition'
